{{- if .Values.auth.apiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kure.fullname" . }}-auth
  labels:
    {{- include "kure.labels" . | nindent 4 }}
type: Opaque
data:
  api-key: {{ .Values.auth.apiKey | b64enc | quote }}
{{- end }}
