{{- /*
Namespace is created by Helm with --create-namespace flag.
This template adds Pod Security Admission labels to the namespace.
Note: Helm doesn't support patching namespaces it creates, so this
only works when the namespace is pre-created or on upgrade.
*/ -}}
